#!/usr/bin/env bash
# OpenSuperFin one-line installer
# Usage: curl -fsSL https://raw.githubusercontent.com/tedboudros/OpenSuperFin/main/install.sh | bash

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color
BOLD='\033[1m'

info()  { echo -e "${CYAN}[INFO]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
fail()  { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

REPO="https://github.com/tedboudros/OpenSuperFin.git"
INSTALL_DIR="${OPENSUPERFIN_INSTALL_DIR:-$HOME/OpenSuperFin}"
BIN_DIR="${HOME}/.local/bin"

echo ""
echo -e "${BOLD}  ___                   ____                        _____ _       ${NC}"
echo -e "${BOLD} / _ \\ _ __   ___ _ __ / ___| _   _ _ __   ___ _ __|  ___(_)_ __  ${NC}"
echo -e "${BOLD}| | | | '_ \\ / _ \\ '_ \\\\___ \\| | | | '_ \\ / _ \\ '__|  |_  | | '_ \\ ${NC}"
echo -e "${BOLD}| |_| | |_) |  __/ | | |___) | |_| | |_) |  __/ |  |  _| | | | | |${NC}"
echo -e "${BOLD} \\___/| .__/ \\___|_| |_|____/ \\__,_| .__/ \\___|_|  |_|   |_|_| |_|${NC}"
echo -e "${BOLD}      |_|                          |_|                             ${NC}"
echo ""
echo -e "  ${CYAN}One-line installer${NC}"
echo ""

# -------------------------------------------------------------------
# Step 1: Check Python
# -------------------------------------------------------------------
info "Checking Python..."

PYTHON=""
for cmd in python3.13 python3.12 python3 python; do
    if command -v "$cmd" &>/dev/null; then
        version=$("$cmd" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" 2>/dev/null)
        major=$(echo "$version" | cut -d. -f1)
        minor=$(echo "$version" | cut -d. -f2)
        if [ "$major" -ge 3 ] && [ "$minor" -ge 11 ]; then
            PYTHON="$cmd"
            break
        fi
    fi
done

if [ -z "$PYTHON" ]; then
    fail "Python 3.11+ is required but not found. Install it first:
    macOS: brew install python@3.12
    Ubuntu: sudo apt install python3.12 python3.12-venv
    Other: https://www.python.org/downloads/"
fi

ok "Found $($PYTHON --version)"

# -------------------------------------------------------------------
# Step 2: Clone or update the repo
# -------------------------------------------------------------------
if [ -d "$INSTALL_DIR/.git" ]; then
    info "Updating existing installation at $INSTALL_DIR..."
    cd "$INSTALL_DIR"
    git pull --quiet
    ok "Updated to latest version"
else
    info "Cloning OpenSuperFin to $INSTALL_DIR..."
    git clone --quiet "$REPO" "$INSTALL_DIR"
    ok "Cloned successfully"
fi

cd "$INSTALL_DIR"

# -------------------------------------------------------------------
# Step 3: Create virtual environment
# -------------------------------------------------------------------
if [ ! -d ".venv" ]; then
    info "Creating virtual environment..."
    "$PYTHON" -m venv .venv
    ok "Virtual environment created"
else
    ok "Virtual environment exists"
fi

# -------------------------------------------------------------------
# Step 4: Install dependencies
# -------------------------------------------------------------------
info "Installing dependencies..."
.venv/bin/pip install --quiet --upgrade pip
.venv/bin/pip install --quiet -r requirements.txt
.venv/bin/pip install --quiet questionary
ok "Dependencies installed"

# -------------------------------------------------------------------
# Step 5: Create the `opensuperfin` CLI wrapper
# -------------------------------------------------------------------
info "Creating CLI command..."

mkdir -p "$BIN_DIR"

cat > "$BIN_DIR/opensuperfin" << WRAPPER
#!/usr/bin/env bash
# OpenSuperFin CLI wrapper -- auto-generated by install.sh
cd "$INSTALL_DIR" && .venv/bin/python -m cli.main "\$@"
WRAPPER

chmod +x "$BIN_DIR/opensuperfin"

# Check if BIN_DIR is in PATH
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    # Detect shell and add to PATH
    SHELL_NAME=$(basename "$SHELL")
    RC_FILE=""

    case "$SHELL_NAME" in
        zsh)  RC_FILE="$HOME/.zshrc" ;;
        bash) RC_FILE="$HOME/.bashrc" ;;
        fish) RC_FILE="$HOME/.config/fish/config.fish" ;;
    esac

    if [ -n "$RC_FILE" ]; then
        if ! grep -q "$BIN_DIR" "$RC_FILE" 2>/dev/null; then
            echo "" >> "$RC_FILE"
            echo "# OpenSuperFin" >> "$RC_FILE"
            if [ "$SHELL_NAME" = "fish" ]; then
                echo "set -gx PATH $BIN_DIR \$PATH" >> "$RC_FILE"
            else
                echo "export PATH=\"$BIN_DIR:\$PATH\"" >> "$RC_FILE"
            fi
            warn "Added $BIN_DIR to PATH in $RC_FILE"
            warn "Run 'source $RC_FILE' or open a new terminal for the 'opensuperfin' command"
        fi
    fi

    # Also export for the current session
    export PATH="$BIN_DIR:$PATH"
fi

ok "CLI command installed: opensuperfin"

# -------------------------------------------------------------------
# Done!
# -------------------------------------------------------------------
echo ""
ok "Installation complete!"
echo ""
echo -e "  Run this now to configure OpenSuperFin:"
echo ""
echo -e "    ${BOLD}opensuperfin setup${NC}"
echo ""
