"""Config generator -- produces config.yaml + .env from setup wizard choices.

Reads PLUGIN_META config_fields to know which values are secrets (-> .env)
and which are regular settings (-> config.yaml).
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import yaml

from cli.scanner import PluginInfo

logger = logging.getLogger(__name__)


def generate_config(
    home_dir: Path,
    enabled_plugins: list[PluginInfo],
    plugin_values: dict[str, dict[str, Any]],
    server_host: str = "127.0.0.1",
    server_port: int = 8321,
) -> tuple[Path, Path]:
    """Generate config.yaml and .env files from setup wizard results.

    Args:
        home_dir: The OpenSuperFin home directory (~/.opensuperfin)
        enabled_plugins: List of plugins the user enabled
        plugin_values: {plugin_name: {field_key: value}} for each plugin
        server_host: HTTP server bind host
        server_port: HTTP server bind port

    Returns:
        Tuple of (config_path, env_path)
    """
    home_dir.mkdir(parents=True, exist_ok=True)

    config: dict[str, Any] = {}
    secrets: dict[str, str] = {}

    config["home_dir"] = str(home_dir)
    config["server"] = {"host": server_host, "port": server_port}

    # Group plugins by category and build config sections
    for plugin in enabled_plugins:
        values = plugin_values.get(plugin.name, {})
        _add_plugin_to_config(config, secrets, plugin, values)

    # Write config.yaml
    config_path = home_dir / "config.yaml"
    with open(config_path, "w") as f:
        f.write("# OpenSuperFin Configuration\n")
        f.write("# Generated by opensuperfin setup\n")
        f.write("# Edit freely -- re-run 'opensuperfin config' to regenerate\n\n")
        yaml.dump(config, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    # Write .env
    env_path = home_dir / ".env"
    with open(env_path, "w") as f:
        f.write("# OpenSuperFin Secrets\n")
        f.write("# Generated by opensuperfin setup\n")
        f.write("# NEVER commit this file to git\n\n")
        for key, value in sorted(secrets.items()):
            f.write(f"{key}={value}\n")

    logger.info("Config written to %s", config_path)
    logger.info("Secrets written to %s", env_path)

    return config_path, env_path


def _add_plugin_to_config(
    config: dict,
    secrets: dict,
    plugin: PluginInfo,
    values: dict[str, Any],
) -> None:
    """Add a plugin's configuration to the config dict and secrets dict."""
    category = plugin.category

    # Map category to config section
    section_map = {
        "ai_provider": "ai",
        "market_data": "market_data",
        "integration": "integrations",
        "agent": "ai",
        "risk_rule": "risk",
        "task_handler": "scheduler",
    }
    section = section_map.get(category, category)

    for field in plugin.config_fields:
        value = values.get(field.key, field.default)
        if value is None:
            continue

        if field.type == "secret" and field.env_var:
            # Secrets go to .env, config.yaml gets ${ENV_VAR} reference
            secrets[field.env_var] = str(value)
            value = f"${{{field.env_var}}}"

        if field.type == "number" and isinstance(value, str):
            try:
                value = float(value)
                if value == int(value):
                    value = int(value)
            except ValueError:
                pass

    # Build the config structure based on category
    if category == "ai_provider":
        providers = config.setdefault("ai", {}).setdefault("providers", {})
        provider_config: dict[str, Any] = {"enabled": True}
        for field in plugin.config_fields:
            val = values.get(field.key, field.default)
            if val is None:
                continue
            if field.type == "secret" and field.env_var:
                provider_config[field.key] = f"${{{field.env_var}}}"
            elif field.type == "number":
                try:
                    val = float(val)
                    if val == int(val):
                        val = int(val)
                except (ValueError, TypeError):
                    pass
                provider_config[field.key] = val
            else:
                provider_config[field.key] = val
        providers[plugin.name] = provider_config

        # Set first provider as default if not already set
        if "default_provider" not in config.get("ai", {}):
            config.setdefault("ai", {})["default_provider"] = plugin.name

    elif category == "market_data":
        md = config.setdefault("market_data", {}).setdefault("providers", {})
        provider_config = {"enabled": True}
        for field in plugin.config_fields:
            val = values.get(field.key, field.default)
            if val is not None:
                provider_config[field.key] = val
        md[plugin.name] = provider_config

    elif category == "integration":
        integ = config.setdefault("integrations", {})
        integ_config: dict[str, Any] = {"enabled": True}
        channels: list[dict] = []
        channel: dict[str, Any] = {}
        for field in plugin.config_fields:
            val = values.get(field.key, field.default)
            if val is None:
                continue
            if field.type == "secret" and field.env_var:
                integ_config[field.key] = f"${{{field.env_var}}}"
            elif field.key in ("chat_id", "direction"):
                channel[field.key] = val
            else:
                integ_config[field.key] = val
        if channel:
            channel.setdefault("id", "default")
            channel.setdefault("direction", "both")
            channels.append(channel)
            integ_config["channels"] = channels
        integ[plugin.name] = integ_config

    elif category == "risk_rule":
        rules = config.setdefault("risk", {}).setdefault("rules", {})
        rule_config: dict[str, Any] = {}
        for field in plugin.config_fields:
            val = values.get(field.key, field.default)
            if val is not None:
                if field.type == "number":
                    try:
                        val = float(val)
                        if val == int(val):
                            val = int(val)
                    except (ValueError, TypeError):
                        pass
                rule_config[field.key] = val
        rules[plugin.name] = rule_config

    elif category == "task_handler":
        tasks = config.setdefault("scheduler", {}).setdefault("handlers", {})
        handler_config: dict[str, Any] = {}
        for field in plugin.config_fields:
            val = values.get(field.key, field.default)
            if val is not None:
                handler_config[field.key] = val
        tasks[plugin.name] = handler_config

    elif category == "agent":
        agents = config.setdefault("ai", {}).setdefault("agents", {})
        agents[plugin.name] = {"enabled": True, "description": plugin.description}
