"""Memory model -- structured learnings from AI-vs-human divergences."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal
from uuid import uuid4

from pydantic import BaseModel, Field


class Memory(BaseModel):
    """A structured learning generated by the comparison task.

    Stored as JSON files in memories/ and indexed in SQLite for fast retrieval.
    Included in future ContextPacks so the AI adjusts behavior based on past
    divergences with the human.
    """

    id: str = Field(default_factory=lambda: f"mem_{uuid4().hex[:12]}")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    signal_id: str | None = None

    # The divergence
    divergence_type: Literal[
        "human_skipped",
        "human_modified",
        "human_initiated",
        "timing_divergence",
    ]
    ai_action: str
    human_action: str

    # The outcome
    outcome_period: str = ""
    outcome: str = ""
    ai_pnl: float | None = None
    human_pnl: float | None = None
    who_was_right: Literal["ai", "human", "both", "neither"] = "neither"

    # The lesson
    lesson: str = ""
    tags: list[str] = Field(default_factory=list)
    confidence_impact: float = 0.0

    # Usage tracking
    referenced_in_decisions: int = 0

    # Source tracking
    source: Literal["production", "simulation"] = "production"
